### ISSUE TITLE
Curious what this is for

### ISSUE THREAD

**Issue by parker-codes** [matt-ramotar/coda-api-node#1]
Hey, I saw that you forked the coda-js repo and then started building your own. There's nothing wrong with that, but I'm curious why you wanted to build your own instead of using that one or contributing to it. It already has a lot of people using it.

**Comment by matt-ramotar** [comment]
Hey Parker - Just building for fun. Not planning to publish. Several tools and technologies I've wanted to explore, and I love Coda. I really appreciate your reaching out and the work you've done on coda-js. Let me know if I can help tackle the migration, Matt

**Comment by parker-codes** [comment]
Oh, that sounds fun. That's why I originally built coda-js as well! 😁 We haven't had any takers on the migration to v1 yet, so if that's something you'd like to do, go for it! I just created a `v1-migration` branch, and will review any PRs that come through. Check out https://github.com/parker-codes/coda-js/issues/12 for a breakdown.

**Comment by matt-ramotar** [comment]
Thanks Parker! Just forked and subscribed. Looking forward to it
